### ISSUE TITLE
Implement a custom optimizer for training

### ISSUE THREAD

**Issue by duynht** [trungdt21/svm-from-scratch#4]
# Task 4: Implement a custom optimizer for training
- [ ] SMO (Sequential Minimizing Optimizer): Bishop's + cs 229
- [Recommend read: Numerical Optimization](https://www.csie.ntu.edu.tw/~r97002/temp/num_optimization.pdf)

**Comment by duynht** [comment]
I'll try out this task

**Comment by v-trungdt21** [comment]
implemented
